### ISSUE TITLE
Can't access Web GUI

### ISSUE THREAD

**Issue by clemkofi** [sfuhrm/docker-opendaylight#2]
Hello, I'm quite new to ODL and after running the image I can't seem to access the Web GUI. Any help with this would greatly be appreciated.
<img width="1328" alt="Screen Shot 2021-09-18 at 7 21 04 PM" src="https://user-images.githubusercontent.com/25843865/133897170-26345ef1-62bb-4703-9c2a-d02443df12ae.png">
.

**Comment by sfuhrm** [comment]
Hi @clemkofi 

in the past, you had to [install the modules for the DLUX frontend](https://docs.opendaylight.org/en/stable-nitrogen/getting-started-guide/common-features/dlux.html) before using it.
AFAIK the web gui DLUX was removed at some release because no one wanted to support it, but I don't remember which. So you need to work with the CLI and/or REST interface or use an older version of ODL.

I'm not part of the core team of OpenDaylight, so it's probably better to take a look at the documentation and possibly take a look at their [github repo](https://github.com/opendaylight/).

Hope this helps.

Stephan
